# Generated by Django 4.1 on 2023-06-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbladmin',
            name='std_ID',
        ),
        migrations.AddField(
            model_name='tbladmin',
            name='admin_ID',
            field=models.CharField(default='16201519001', max_length=12, primary_key=True, serialize=False),
        ),
    ]
