# Generated by Django 4.1 on 2023-06-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_tbladmin_std_id_tbladmin_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbluser',
            fields=[
                ('user_ID', models.CharField(default='2221519001', max_length=12, primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('user_email_ID', models.EmailField(max_length=254)),
                ('user_password', models.CharField(default='', max_length=50)),
                ('user_address', models.CharField(default='', max_length=250)),
                ('user_mobile_number', models.CharField(default='', max_length=10)),
                ('profilepicture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='tblbookings',
            fields=[
                ('booking_ID', models.CharField(default='2221519001', max_length=12, primary_key=True, serialize=False)),
                ('booking_total_amount', models.FloatField()),
                ('booking_advance_amount', models.FloatField()),
                ('bookihg_balance_amount', models.FloatField()),
                ('booking_dates', models.DateField()),
                ('booking_admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.tbladmin')),
                ('booking_user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.tbluser')),
            ],
        ),
    ]
