# Generated by Django 4.1 on 2023-06-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbladmin',
            fields=[
                ('std_ID', models.CharField(default='16201519-001', max_length=12, primary_key=True, serialize=False)),
                ('admin_firstname', models.CharField(default='', max_length=50)),
                ('admin_lastname', models.CharField(default='', max_length=50)),
                ('admin_emailID', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(default='', max_length=50)),
                ('hall_name', models.CharField(default='', max_length=50)),
                ('hall_address', models.CharField(default='', max_length=250)),
                ('hall_price', models.FloatField()),
                ('hall_capasity', models.IntegerField()),
                ('admin_mobile', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
